### ISSUE TITLE
Graceful shutdown

### ISSUE THREAD

**Issue by alexander-melentyev** [zhashkevych/courses-backend#30]
Ребят, привет!
https://github.com/zhashkevych/courses-backend/blob/93261b2403c8198ec1f123b883481be30e5ff1d6/internal/app/app.go#L120 - здесь прилетает ошибка http.ErrServerClosed - и это нормально - потому что сервер реально закрывается - может добавить еще проверку?

**Comment by alyakimenko** [comment]
Мне кажется, отличная идея, учитывая, что в этом случае, `err` никогда не будет `nil`.
Можно сделать что-то вроде:
```go
if err := srv.Stop(ctx); err != http.ErrServerClosed {
    logrus.Errorf("failed to stop server: %w", err)
}
```

**Comment by alexander-melentyev** [comment]
Лучше даже так:
`
if err := srv.Stop(ctx); !errors.Is(err, http.ErrServerClosed) {
    logger.Errorf("failed to stop server: %w", err)
}
`
Проверяем по канонам на ошибку, + используем свой логгер, как завещал @zhashkevych

**Comment by alexander-melentyev** [comment]
Хотя стоп, ошибку нужно проверять вот тут:
```go
	go func() {
		if err := srv.Run(); !errors.Is(err, http.ErrServerClosed) {
			logger.Errorf("error occurred while running http server: %s\n", err.Error())
		}
	}()
```

Или чуть переписать

**Comment by alexander-melentyev** [comment]
Создал PR: https://github.com/zhashkevych/courses-backend/pull/36
